dependencies {
    api(project(":javalin-security"))
    api(project(":javalin-security-extensions-common"))
    compileOnly(libs.nimbus.jose.jwt)
    compileOnly(libs.auth0.java.jwt)
    compileOnly(libs.auth0.jwks.rsa)
    compileOnly(libs.javalin)
    compileOnly(libs.slf4j.api)

    testImplementation(libs.javalin)
    testImplementation(libs.javalin.testtools)
    testImplementation(libs.nimbus.jose.jwt)
    testImplementation(libs.auth0.java.jwt)
    testImplementation(libs.auth0.jwks.rsa)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj.core)
    testImplementation(libs.mockk)
    testRuntimeOnly(libs.junit.platform.launcher)
}
